BcBundle\Entity\Libreria:
    type: entity
    table: libreria
    id:
        idLibreria:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_libreria
            generator:
                strategy: IDENTITY
    fields:
        nif:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
        nombre:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        tlf:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        poblacion:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        provincia:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        direccion:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        ubicacion:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        web:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
