bc_homepage:
    path:   /
    defaults: { _controller: BcBundle:Default:index }
    
bc_add_libro:
    path: /libro/addLibro
    defaults: { _controller: BcBundle:Libro:addLibro }
    
bc_index_libro:
    path: /libro
    defaults: { _controller: BcBundle:Libro:indexLibro }
    
bc_index_libroValid:
    path: /libroValid
    defaults: { _controller: BcBundle:Libro:indexLibro }
    
bc_edit_libro:
    path: /libro/edit/{id}
    defaults: { _controller: BcBundle:Libro:editLibro }    

bc_val_libro:
    path: /libro/val/{id}
    defaults: { _controller: BcBundle:Libro:valLibro }

bc_delete_libro:
    path: /libro/delete/{id}
    defaults: { _controller: BcBundle:Libro:delLibro}
    
bc_add_autor:
    path: /autor/addAutor
    defaults: { _controller: BcBundle:Autor:addAutor }

bc_index_autor:
    path: /autor
    defaults: { _controller: BcBundle:Autor:indexAutor }

bc_edit_autor:
    path: /autor/edit/{id}
    defaults: { _controller: BcBundle:Autor:editAutor }   
  
bc_delete_autor:
    path: /autor/delete/{id}
    defaults: { _controller: BcBundle:Autor:delAutor }
   
bc_add_libreria:
    path: /libreria/addLibreria
    defaults: { _controller: BcBundle:Libreria:addLibreria }

bc_index_libreria:
    path: /libreria
    defaults: { _controller: BcBundle:Libreria:indexLibreria }

bc_delete_libreria:
    path: /libreria/delete/{id}
    defaults: { _controller: BcBundle:Libreria:delLibreria }
    
bc_edit_libreria:
    path: /libreria/edit/{id}
    defaults: { _controller: BcBundle:Libreria:editLibreria }

bc_index_listadolibros:
    path: /listadolibro/index/{id}
    defaults: { _controller: BcBundle:Listadolibro:indexListadolibro }
    
bc_index_stocks:
    path: /stock/index/{id}
    defaults: { _controller: BcBundle:Stock:indexStock }    
    
login:
    path: /login
    defaults: { _controller: BcBundle:Usuario:login }
    
login_check:
    path: /login_check

logout:
    path: /logout

bc_menu:
    path: /menu
    defaults: { _controller: BcBundle:Default:menu}
    
bc_menu:
    path: /menu/find
    defaults: { _controller: BcBundle:Default:indexFind}