bc_homepage:
    path:   /
    defaults: { _controller: BcBundle:Usuario:Login }

bc_perfil_usuario:
    path: /usuario/{id}
    defaults: { _controller: BcBundle:Usuario:perfilUsuario }   

bc_index_usuario:
    path: /usuario
    defaults: { _controller: BcBundle:Usuario:indexUsuario }    

bc_del_usuario:
    path: /usuario/delete/{id}
    defaults: { _controller: BcBundle:Usuario:delUsuario } 
 
bc_edit_usuario:
    path: /usuario/edit/{id}
    defaults: { _controller: BcBundle:Usuario:editUsuario } 
    
bc_add_libro:
    path: /libro/addLibro
    defaults: { _controller: BcBundle:Libro:addLibro }

bc_edit_libro:
    path: /libro/edit/{id}
    defaults: { _controller: BcBundle:Libro:editLibro }    

bc_perfil_libro:
    path: /libro/perfilLibro/{id}
    defaults: { _controller: BcBundle:Libro:perfilLibro }

bc_delete_libro:
    path: /libro/delLibro/{id}
    defaults: { _controller: BcBundle:Libro:delLibro}   
    
bc_find_libro:
    path: /libro/findLibro
    defaults: { _controller: BcBundle:Libro:findLibro }    

bc_result_libro:
    path: /libro/resultLibro/
    defaults: { _controller: BcBundle:Libro:resultLibroVal }    
   
bc_index_libro:
    path: /libro/{page}{size}
    defaults: { _controller: BcBundle:Libro:indexLibroVal,page:1,size:2 }

bc_index_NoVallibro:
    path: /libroValidacion
    defaults: { _controller: BcBundle:Libro:indexLibroNoVal }    

bc_validar:
    path: /libroValidacion/{id}
    defaults: { _controller: BcBundle:Libro:Validar }
    
bc_add_autor:
    path: /autor/addAutor
    defaults: { _controller: BcBundle:Autor:addAutor }

bc_lib_autor:
    path: /autor/libAutor/{id}
    defaults: { _controller: BcBundle:Autor:listLibAutor }

bc_index_autor:
    path: /autor
    defaults: { _controller: BcBundle:Autor:indexAutor }

bc_edit_autor:
    path: /autor/edit/{id}
    defaults: { _controller: BcBundle:Autor:editAutor }   
  
bc_delete_autor:
    path: /autor/delAutor/{id}
    defaults: { _controller: BcBundle:Autor:delAutor }

bc_perfil_autor:
    path: /autor/{id}
    defaults: { _controller: BcBundle:Autor:perfilAutor }     
   
bc_add_libreria:
    path: /libreria/addLibreria
    defaults: { _controller: BcBundle:Libreria:addLibreria }

bc_index_libreria:
    path: /libreria
    defaults: { _controller: BcBundle:Libreria:indexLibreria }

bc_perfil_libreria:
    path: /libreria/{id}
    defaults: { _controller: BcBundle:Libreria:perfilLibreria }

bc_delete_libreria:
    path: /libreria/delLibreria/{id}
    defaults: { _controller: BcBundle:Libreria:delLibreria }
    
bc_edit_libreria:
    path: /libreria/edit/{id}
    defaults: { _controller: BcBundle:Libreria:editLibreria }

bc_index_listadolibros:
    path: /listadolibro/index/{id}
    defaults: { _controller: BcBundle:Listadolibro:indexListadolibro }

bc_add_listadolibros:
    path: /listadolibro/addListaLibro/{idusuario},{idlibro}
    defaults: { _controller: BcBundle:Listadolibro:addListadolibro }

bc_del_listadolibros:
    path: /listadolibros/delListaLibro/{idusuario},{idlibro}
    defaults: { _controller: BcBundle:Listadolibro:delListadolibro }  
  
bc_index_stocks:
    path: /stock/index/{id}
    defaults: { _controller: BcBundle:Stock:indexStock }    

bc_index_find:
    path: /indexFind
    defaults: { _controller: BcBundle:Default:indexFind }
  
login:
    path: /login
    defaults: { _controller: BcBundle:Usuario:login }
    
login_check:
    path: /login_check

logout:
    path: /logout

    
