bc_homepage:
    path:   /
    defaults: { _controller: BcBundle:Default:index }
    
bc_add_libro:
    path: /libro/addLibro
    defaults: { _controller: BcBundle:Libro:addLibro }
    
bc_index_libro:
    path: /libro
    defaults: { _controller: BcBundle:Libro:indexLibro }
    
bc_delete_libro:
    path: /libro/delete/{id}
    defaults: { _controller: BcBundle:Libro:delLibro}
    
bc_add_autor:
    path: /autor/addAutor
    defaults: { _controller: BcBundle:Autor:addAutor }

bc_index_autor:
    path: /autor
    defaults: { _controller: BcBundle:Autor:indexAutor }
    
bc_delete_autor:
    path: /autor/delete/{id}
    defaults: { _controller: BcBundle:Autor:delAutor }
   
bc_add_libreria:
    path: /libreria/addLibreria
    defaults: { _controller: BcBundle:Libreria:addLibreria }

bc_index_libreria:
    path: /libreria
    defaults: { _controller: BcBundle:Libreria:indexLibreria }

bc_delete_libreria:
    path: /autor/libreria/{id}
    defaults: { _controller: BcBundle:Libreria:delLibreria }

login:
    path: /login
    defaults: { _controller: BcBundle:Usuario:login }
    
login_check:
    path: /login_check

logout:
    path: /logout

bc_menu:
    path: /menu
    defaults: { _controller: BcBundle:Default:menu}